// MIT License
//
// # Copyright (c) 2026 Christopher J Bearman
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
package test

import (
	"fmt"
	"os"
	"path/filepath"
	"testing"
)

// Example files generated by tests will go here
const (
	testOutputDir = "test_outputs"
)

// firstReturn is useful for testing getters, it discards the second
// return value of a two return function allowing quicker assertions
func firstReturn(ret1, ret2 any) any {
	return ret1
}

// recordTestOutput will record, into our output dir, a tag
// binary, or YAML (or other output file)
func recordTestOutput(t *testing.T, suffix string, data []byte) {
	_ = os.Mkdir(testOutputDir, 0755)

	outputName := filepath.Join(testOutputDir, fmt.Sprintf("%s.%s", t.Name(), suffix))
	_ = os.Remove(outputName)
	err := os.WriteFile(outputName, data, 0644)
	if err != nil {
		t.Logf("Failed to write output file %s: %v", outputName, err)
	} else {
		t.Logf("Wrote output file: %s, length %d", outputName, len(data))
	}
}
